# SPDX-License-Identifier: GPL-2.0
#
# ASK 2.0 - out-of-tree kernel module Kbuild
#
# PR1: skeleton only. Compiles into a single ask.ko containing
# the genl family registration + ASK_CMD_GET_INFO. All other
# subsystems are init/exit stubs that will be filled in by later PRs.

ccflags-y += -I$(src)/include
ccflags-y += -I$(src)/include/uapi

obj-$(CONFIG_NET_ASK) += ask.o

ask-y := \
ask_main.o \
ask_genl.o \
ask_genl_attr.o \
ask_flow.o \
ask_flow_offload.o \
ask_xfrm.o \
ask_caam.o \
ask_bridge.o \
ask_neigh.o \
ask_op.o \
ask_hostcmd.o \
ask_stats.o \
ask_debugfs.o