#!/bin/bash
# fancontrol-setup — dynamically generates /etc/fancontrol with correct hwmon numbers
# hwmon numbering is unstable across boots; this script finds devices by name/capability
# and writes the config before fancontrol.service starts.
#
# Temperature source priority:
#   1. core_cluster or cluster_thermal (thermal zone — mainline vs SDK naming)
#   2. GPY115C PHY hwmon (SDK kernel fallback — PHY on-die temp is a good proxy)
#
# Runs as ExecStartPre= in fancontrol.service override.

set -euo pipefail

# Find hwmon number by name
find_hwmon() {
    local target_name="$1"
    for h in /sys/class/hwmon/hwmon*; do
        local name
        name=$(cat "$h/name" 2>/dev/null) || continue
        if [ "$name" = "$target_name" ]; then
            basename "$h"
            return 0
        fi
    done
    return 1
}

# Find first hwmon with temp1_input on the FMan MDIO bus (GPY115C PHY)
# These are on-die PHY sensors at ~61°C — good proxy for SoC temperature.
find_phy_hwmon() {
    for h in /sys/class/hwmon/hwmon*; do
        [ -f "$h/temp1_input" ] || continue
        local devpath
        devpath=$(readlink -f "$h/device" 2>/dev/null) || continue
        # Match FMan MDIO bus path (GPY115C PHYs)
        if echo "$devpath" | grep -q "fman.*mdio"; then
            basename "$h"
            return 0
        fi
    done
    return 1
}

# Board detection — only run on LS1046A
compat="/proc/device-tree/compatible"
if [ ! -f "$compat" ] || ! tr '\0' '\n' < "$compat" | grep -q "fsl,ls1046a"; then
    exit 0  # not our board, skip silently
fi

EMC=$(find_hwmon "emc2305") || { echo "ERROR: EMC2305 fan controller not found" >&2; exit 1; }

# Try core_cluster / cluster_thermal first, fall back to PHY temp (SDK kernel)
TEMP_SRC=""
TEMP_NAME=""
if TEMP_SRC=$(find_hwmon "core_cluster"); then
    TEMP_NAME="core_cluster"
elif TEMP_SRC=$(find_hwmon "cluster_thermal"); then
    TEMP_NAME="cluster_thermal"
elif TEMP_SRC=$(find_phy_hwmon); then
    TEMP_NAME=$(cat "/sys/class/hwmon/$TEMP_SRC/name" 2>/dev/null || echo "phy")
else
    echo "ERROR: no temperature source found (no core_cluster, no PHY hwmon)" >&2
    exit 1
fi

EMC_PATH=$(readlink -f "/sys/class/hwmon/$EMC/device" | sed 's|^/sys/||')
TEMP_PATH=$(readlink -f "/sys/class/hwmon/$TEMP_SRC/device" | sed 's|^/sys/||')

cat > /etc/fancontrol << EOF
# Auto-generated by fancontrol-setup — do not edit manually
# EMC2305 PWM fan → ${TEMP_NAME} temperature sensor
# Linear ramp: 40°C (off) → 51 PWM (spin-up) → 255 PWM (80°C full)
INTERVAL=10
DEVPATH=${EMC}=${EMC_PATH} ${TEMP_SRC}=${TEMP_PATH}
DEVNAME=${EMC}=emc2305 ${TEMP_SRC}=${TEMP_NAME}
FCTEMPS=${EMC}/pwm1=${TEMP_SRC}/temp1_input
FCFANS=${EMC}/pwm1=${EMC}/fan1_input
MINTEMP=${EMC}/pwm1=40
MAXTEMP=${EMC}/pwm1=80
MINSTART=${EMC}/pwm1=51
MINSTOP=${EMC}/pwm1=34
MINPWM=${EMC}/pwm1=0
MAXPWM=${EMC}/pwm1=255
AVERAGE=${EMC}/pwm1=1
EOF

echo "fancontrol-setup: EMC2305=$EMC temp=$TEMP_SRC ($TEMP_NAME) → /etc/fancontrol"

